version: "3"

services:
    devcontainer:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VARIANT: "3.8"
                NODE_VERSION: "lts/*"
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
