version: "3"

services:
    devcontainer:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VARIANT: "3.8"
                NODE_VERSION: "lts/*"
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
    jobmanager:
        image: pyflink/playgrounds:1.13.0-rc2
        volumes:
            - ./examples:/opt/examples
        command: jobmanager
        environment:
            - JOB_MANAGER_RPC_ADDRESS=localhost
        network_mode: service:devcontainer
    taskmanager:
        image: pyflink/playgrounds:1.13.0-rc2
        volumes:
            - ./examples:/opt/examples
        depends_on:
            - jobmanager
        command: taskmanager
        links:
            - jobmanager:jobmanager
        environment:
            - JOB_MANAGER_RPC_ADDRESS=localhost
            - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=20
        network_mode: service:devcontainer
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        network_mode: service:devcontainer
    kafka:
        image: wurstmeister/kafka:2.12-2.2.1
        ports:
            - "9092"
        depends_on:
            - zookeeper
        environment:
            HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
            KAFKA_ZOOKEEPER_CONNECT: localhost:2181
            KAFKA_CREATE_TOPICS: "Rides:1:1, Fares:1:1, DriverChanges:1:1, TempResults:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: service:devcontainer
